stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
      - data/raw/dataset_phishing.csv

  data_validation:
    cmd: python src/data_validation.py
    deps:
      - src/data_ingestion.py
      - src/data_validation.py
      - data/raw/dataset_phishing.csv
    outs:
      - reports/validation

  preprocess:
    cmd: python src/data_preprocess.py
    deps:
      - src/data_preprocess.py
      - src/data_ingestion.py
      - data/raw/dataset_phishing.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/data_train.py
    deps:
      - src/data_train.py
      - src/data_preprocess.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/best_model.pkl
      - config/best_model.json
      - reports/model_eval